### PR TITLE
Add Elementary OS to certinstall conditional

### PR DESCRIPTION
**Pull request by gsumpster**
### Description
Added a check for 'elementary' to the Debian distribution check conditional, let me know if you'd prefer if I added the full 'elementary OS' to avoid any potential conflicts!

### Related issues
#323

### CODE REVIEW

**Comment by jasonmccallister** [comment]
Thank you @gsumpster I think this should work as intended!

Slightly related since you are on Elementary OS, are you using the default browser Epiphany? We are working on documenting the process for setting up valid TLS on Linux environments and we are not sure if people are using the built in browser on EOS? Is that your default or are you using Firefox? 

You can see the WIP docs here (also Linux support should be improved on the release tomorrow) https://github.com/craftcms/docs/blob/3847d77d4ce2ac429b2dc97a21d9c4b6e4701d25/docs/nitro/2.x/linux.md

**Review by jasonmccallister — APPROVED** [review]

**Comment by jasonmccallister** [comment]
@gsumpster I changed the branch and there is a merge conflict, can you make your changes to this file and push? https://github.com/craftcms/nitro/blob/develop/pkg/certinstall/certinstall_linux.go

We split out the package between Darwin and Linux to make it cleaner going forward.

**Review by jasonmccallister — CHANGES_REQUESTED** [review]
@gsumpster I changed the branch to `develop` and there is a merge conflict, can you make your changes to this file and push? https://github.com/craftcms/nitro/blob/develop/pkg/certinstall/certinstall_linux.go

We split out the package between Darwin and Linux to make it cleaner going forward.

**Comment by gsumpster** [comment]
Hey @jasonmccallister, saw that you merged this, do you want me to open a new PR to make this change to develop?

**Comment by gsumpster** [comment]
>Slightly related since you are on Elementary OS, are you using the default browser Epiphany? We are working on documenting the process for setting up valid TLS on Linux environments and we are not sure if people are using the built in browser on EOS? Is that your default or are you using Firefox?

I don't use the default, I usually use Chrome on Elementary as my default browser. That being said, I think just stating that you'll need to add the Nitro CA to the browser (+ where it is located!) and linking to a few specific browser specific instructions should be fine!

**Comment by jasonmccallister** [comment]
Great! I'm using the same on Fedora 34 and Firefox and the certificates are working just fine. 

I'm going to pull in main to develop now and make sure the conflicts are resolved. I might do some work to make this more fool point going forward but it works for now, thank you!!

**Pull request merged**
